### ISSUE TITLE
does not work with python versions > 3.8

### ISSUE THREAD

**Issue by Khachatur96** [AuthorizeNet/sdk-python#158]
class _PluralBinding (collections.MutableSequence):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableSequence'

**Comment by gnongsie** [comment]
The Python SDK has been tested successfully on v3.6 to v3.12.
We have replaced the offending serialization library with a newer one, which will hopefully not cause more issues like this.
Closing this issue based on that.
