### ISSUE TITLE
Python 3.10 Support

### ISSUE THREAD

**Issue by sunsoftdev** [AuthorizeNet/sdk-python#154]
This SDK won't work on python 3.10 which is the latest version released last year. This version has deprecated the collections need to update that so it can be used for the latest version. It is a core vulneabliity.  Unless the code is updated for this change, this library cannot be used. I have posted a message to the authorize.net support also but no one responded. Does authorize.net still support python and Django or not.

**Comment by ckanoab** [comment]
I'm using 3.10 and I got an error `AttributeError: module 'collections' has no attribute 'MutableSequence'` from the pyxb library at `pyxb/binding/content.py`. Googling that error led me to [https://stackoverflow.com/questions/70284852/couldnt-run-the-py-file-attributeerror-module-collections-has-no-attribut](url) 
I then opened the `content.py` file and found the `import collections` line and changed it to `import collections.abc as collections` and that got my script to run

**Comment by smithaldon1** [comment]
@ckanoab I just ran into this and can confirm that this worked for me as well!

**Comment by Rohith-sreedharan** [comment]
@ckanoab same i ran through this issue and can confirm that this worked for me as well!

**Comment by billalive** [comment]
Thanks @ckanoab ! Worked for me as well.

I hope this is fixed in the next release; it's a tiny, easy fix.

**Comment by scottie** [comment]
Crazy behavior that they leave this open for years and do not care about their customers.

**Comment by developervick** [comment]
![Screenshot from 2024-01-16 17-55-20](https://github.com/AuthorizeNet/sdk-python/assets/104270477/8ac534df-9c1e-412d-ba38-752c6f8b6f35)

Add these line at ../lib/python3.10/site-packages/pyxb/binding/content.py this location will fix your issue

**Comment by dvlprb2** [comment]
@developervick Instead of updating the package file try the below solution.

https://github.com/AuthorizeNet/sdk-python/issues/151#issuecomment-1943155246

**Comment by gnongsie** [comment]
The Python SDK has been tested successfully on v3.6 to v3.12.
We have replaced the offending serialization library with a newer one, which will hopefully not cause more issues like this.
Closing this issue based on that.
